#!/bin/sh
# This file is in the public domain.

set -eu

if ! git --version >/dev/null; then
  echo "git not installed"
  exit 1
fi

if ! pandoc --version >/dev/null; then
  echo "pandoc not installed"
  exit 1
fi


echo "$0: Updating submodules"
echo | git submodule update --init --force --remote

# Generate based on pinned submodule
./contrib/gana-generate.sh

# This is more portable than `which' but comes with
# the caveat of not(?) properly working on busybox's ash:
existence()
{
    command -v "$1" >/dev/null 2>&1
}


if existence uncrustify; then
    echo "Installing uncrustify hook and configuration"
    # Install uncrustify format symlink (if possible)
    ln -s contrib/uncrustify.cfg uncrustify.cfg 2> /dev/null || true
    # Install pre-commit hook (if possible)
    ln -s ../../contrib/uncrustify_precommit .git/hooks/pre-commit 2> /dev/null || true
else
    echo "Uncrustify not detected, hook not installed. Please install uncrustify if you plan on doing development"
fi


# Generate Makefile.am in contrib/
cd contrib
rm -f Makefile.am
find wallet-core/aml-backoffice/ -type f -printf '  %p \\\n' | sort > Makefile.am.ext
# Remove extra '\' at the end of the file
truncate -s -2 Makefile.am.ext
cat Makefile.am.in Makefile.am.ext >> Makefile.am
# Prevent accidental editing of the generated Makefile.am
chmod -w Makefile.am
cd ..

echo "$0: Running autoreconf"
autoreconf -fi
