usr/bin/taler-auditor-*
usr/bin/taler-helper-auditor-*

usr/lib/*/taler-auditor/libtaler_plugin_auditor*.so
usr/lib/*/libauditor*
usr/lib/*/libtalerauditordb*

usr/share/man/man*/taler-auditor*
usr/share/man/man*/taler-helper-auditor*

usr/share/info/taler-auditor*

usr/share/taler-auditor/config.d/*
usr/share/taler-auditor/sql/*
usr/share/taler-auditor/spa/*

# Debian-specific configuration files for /etc/
debian/etc-taler-auditor/* etc/
