#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
  . /usr/share/debconf/confmodule
fi

case "${1}" in
purge)
  rm -rf /var/log/taler-exchange/ /var/lib/taler-exchange /etc/default/taler-exchange
  rm -f /etc/taler-wire.conf /etc/taler-exchange-db.conf /etc/taler-exchange.conf
  ;;

remove | upgrade | failed-upgrade | abort-install | abort-upgrade | disappear) ;;

*)
  echo "postrm called with unknown argument \`${1}'" >&2
  exit 1
  ;;
esac

#DEBHELPER#

exit 0
