--
-- This file is part of TALER
-- Copyright (C) 2014--2022 Taler Systems SA
--
-- TALER is free software; you can redistribute it and/or modify it under the
-- terms of the GNU General Public License as published by the Free Software
-- Foundation; either version 3, or (at your option) any later version.
--
-- TALER is distributed in the hope that it will be useful, but WITHOUT ANY
-- WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
-- A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License along with
-- TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>
--

--------------------------------

CREATE TABLE IF NOT EXISTS exchange_tables
  (table_serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY
  ,name VARCHAR NOT NULL
  ,version VARCHAR NOT NULL
  ,action VARCHAR NOT NULL
  ,partitioned BOOL NOT NULL
  ,by_range BOOL NOT NULL);
COMMENT ON TABLE exchange_tables
  IS 'Tables of the exchange and their status';
COMMENT ON COLUMN exchange_tables.name
  IS 'Base name of the table (without partition/shard)';
COMMENT ON COLUMN exchange_tables.version
  IS 'Version of the DB in which the given action happened';
COMMENT ON COLUMN exchange_tables.action
  IS 'Action to take on the table (e.g. create, alter, constrain, unconstrain, or drop)';
COMMENT ON COLUMN exchange_tables.partitioned
  IS 'TRUE if the table is partitioned';
COMMENT ON COLUMN exchange_tables.by_range
  IS 'TRUE if the table is partitioned by range';


INSERT INTO exchange_tables
    (name
    ,version
    ,action
    ,partitioned
    ,by_range)
  VALUES
    ('denominations', 'exchange-0001', 'create', FALSE, FALSE)
   ,('denomination_revocations', 'exchange-0001', 'create', FALSE, FALSE)
   ,('kyc_alerts', 'exchange-0001', 'create', FALSE, FALSE)
   ,('profit_drains', 'exchange-0001', 'create', FALSE, FALSE)
   ,('auditors', 'exchange-0001', 'create', FALSE, FALSE)
   ,('auditor_denom_sigs', 'exchange-0001', 'create', FALSE, FALSE)
   ,('exchange_sign_keys', 'exchange-0001', 'create', FALSE, FALSE)
   ,('signkey_revocations', 'exchange-0001', 'create', FALSE, FALSE)
   ,('extensions', 'exchange-0001', 'create', FALSE, FALSE)
   ,('wire_fee', 'exchange-0001', 'create', FALSE, FALSE)
   ,('global_fee', 'exchange-0001', 'create', FALSE, FALSE)
   ,('wire_accounts', 'exchange-0001', 'create', FALSE, FALSE)
   ,('work_shards', 'exchange-0001', 'create', FALSE, FALSE)
   ,('revolving_work_shards', 'exchange-0001', 'create', FALSE, FALSE)
   ,('partners', 'exchange-0001', 'create', FALSE, FALSE)
   ,('partner_accounts', 'exchange-0001', 'create', FALSE, FALSE)
   ,('purse_actions', 'exchange-0001', 'create', FALSE, FALSE)
   ,('policy_fulfillments', 'exchange-0001', 'create', FALSE, FALSE) -- bad!
   ,('policy_details', 'exchange-0001', 'create', FALSE, FALSE) -- bad!
   ,('wire_targets''exchange-0001', 'create', TRUE, FALSE)
   ,('legitimization_processes', 'exchange-0001', 'create', TRUE, FALSE)
   ,('legitimization_requirements', 'exchange-0001', 'create', TRUE, FALSE)
   ,('reserves', 'exchange-0001', 'create', TRUE, FALSE)
   ,('reserves_in', 'exchange-0001', 'create', TRUE, FALSE)
   ,('reserves_close', 'exchange-0001', 'create', TRUE, FALSE)
   ,('reserves_open_requests', 'exchange-0001', 'create', TRUE, FALSE)
   ,('reserves_open_deposits', 'exchange-0001', 'create', TRUE, FALSE)
   ,('reserves_out', 'exchange-0001', 'create', TRUE, FALSE)
   ,('reserves_out_by_reserve', 'exchange-0001', 'create', TRUE, FALSE)
   ,('known_coins', 'exchange-0001', 'create', TRUE, FALSE)
   ,('refresh_commitments', 'exchange-0001', 'create', TRUE, FALSE)
   ,('refresh_revealed_coins', 'exchange-0001', 'create', TRUE, FALSE)
   ,('refresh_transfer_keys', 'exchange-0001', 'create', TRUE, FALSE)
   ,('refunds', 'exchange-0001', 'create', TRUE, FALSE)
   ,('deposits', 'exchange-0001', 'create', TRUE, FALSE)
   ,('deposits_by_ready', 'exchange-0001', 'create', TRUE, TRUE)
   ,('deposits_for_matching', 'exchange-0001', 'create', TRUE, TRUE)
   ,('wire_out', 'exchange-0001', 'create', TRUE, FALSE)
   ,('aggregation_transient', 'exchange-0001', 'create', TRUE, FALSE)
   ,('aggregation_tracking', 'exchange-0001', 'create', TRUE, FALSE)
   ,('recoup', 'exchange-0001', 'create', TRUE, FALSE)
   ,('recoup_by_reserve', 'exchange-0001', 'create', TRUE, FALSE)
   ,('recoup_refresh', 'exchange-0001', 'create', TRUE, FALSE)
   ,('prewire', 'exchange-0001', 'create', TRUE, FALSE)
   ,('cs_nonce_locks', 'exchange-0001', 'create', TRUE, FALSE)
   ,('purse_requests', 'exchange-0001', 'create', TRUE, FALSE)
   ,('purse_decision', 'exchange-0001', 'create', TRUE, FALSE)
   ,('purse_merges', 'exchange-0001', 'create', TRUE, FALSE)
   ,('account_merges', 'exchange-0001', 'create', TRUE, FALSE)
   ,('contracts', 'exchange-0001', 'create', TRUE, FALSE)
   ,('history_requests', 'exchange-0001', 'create', TRUE, FALSE)
   ,('close_requests', 'exchange-0001', 'create', TRUE, FALSE)
   ,('purse_deposists', 'exchange-0001', 'create', TRUE, FALSE)
   ,('wads_out', 'exchange-0001', 'create', TRUE, FALSE)
   ,('wads_out_entries', 'exchange-0001', 'create', TRUE, FALSE)
   ,('wads_in', 'exchange-0001', 'create', TRUE, FALSE)
   ,('wads_in_entries', 'exchange-0001', 'create', TRUE, FALSE)
 ON CONFLICT DO NOTHING;



-------------------- Tables ----------------------------

CREATE OR REPLACE FUNCTION create_table_purse_deletion(
  IN shard_suffix VARCHAR DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
BEGIN
  PERFORM create_partitioned_table(
    'CREATE TABLE IF NOT EXISTS %I'
      '(purse_deletion_serial_id BIGINT GENERATED BY DEFAULT AS IDENTITY' -- UNIQUE'
      ',purse_sig BYTEA CHECK (LENGTH(purse_sig)=64)'
      ',XXX VARCHAR NOT NULL'
    ') %s ;'
    ,'purse_deletion'
    ,'PARTITION BY HASH (XXX)'
    ,shard_suffix
  );
  COMMENT ON TABLE purse_deletion
    IS 'signatures affirming explicit purse deletions';
  COMMENT ON COLUMN purse_deletion.purse_sig
    IS 'signature of type XXX';
END
$$;
COMMENT ON FUNCTION create_table_purse_deletion
  IS 'Creates the purse_deletion table';

CREATE OR REPLACE FUNCTION constrain_table_purse_deletion(
  IN partition_suffix VARCHAR
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  EXECUTE FORMAT (
    'ALTER TABLE purse_deletion_' || partition_suffix || ' '
      'ADD CONSTRAINT purse_deletion_' || partition_suffix || '_XXX '
        'UNIQUE (XXX)'
  );
END
$$;

CREATE OR REPLACE FUNCTION alter_create_was_deleted_table_purse_requests (
  IN partition_suffix VARCHAR
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  EXECUTE FORMAT (
    'ALTER TABLE purse_requests_' || partition_suffix ||
    ' ADD COLUMN'
    ' was_deleted BOOLEAN NOT NULL DEFAULT(FALSE)'
  );
END
$$;

INSERT INTO exchange_tables
    (name
    ,version
    ,action
    ,partitioned
    ,by_range)
  VALUES
    ('purse_deletion'
    ,'exchange-0002'
    ,'create'
    ,TRUE
    ,FALSE),
    ('purse_deletion'
    ,'exchange-0002'
    ,'constrain'
    ,TRUE
    ,FALSE),
    ('purse_requests'
    ,'exchange-0002'
    ,'alter_create_was_deleted'
    ,TRUE
    ,FALSE);
