--
-- This file is part of TALER
-- Copyright (C) 2014--2024 Taler Systems SA
--
-- TALER is free software; you can redistribute it and/or modify it under the
-- terms of the GNU General Public License as published by the Free Software
-- Foundation; either version 3, or (at your option) any later version.
--
-- TALER is distributed in the hope that it will be useful, but WITHOUT ANY
-- WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
-- A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License along with
-- TALER; see the file COPYING.  If not, see <http://www.gnu.org/licenses/>
--

-- TODO: The constraints of operation are just for testing

CREATE TABLE auditor_amount_arithmetic_inconsistency
(
    row_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    -- TODO: correct constraintcheck, currently wrong
    --operation BYTEA NOT NULL CHECK (LENGTH(operation)=16),
    operation TEXT NOT NULL PRIMARY KEY,
    exchange_amount taler_amount,
    auditor_amount taler_amount,
    profitable BOOLEAN,
    suppressed BOOLEAN NOT NULL DEFAULT FALSE
);
COMMENT ON TABLE auditor_amount_arithmetic_inconsistency
    IS 'Report a (serious) inconsistency in the exchange''s database with respect to calculations involving amounts';
